export const productsUrl = "http://plush-toy.shop/toylist/"  // get toylist
export const productUrl = "http://plush-toy.shop/toy/"   // get toy
export const refreshTokenUrl = "http://plush-toy.shop/auth/jwt/refresh/" //get a new access token
export const getTokensUrl = "http://plush-toy.shop/auth/jwt/create/" //get a new access and refresh tokens during authorization
export const getPurchasesUrl = "http://plush-toy.shop/cart/purchase/" //get a purchases from the shopping cart
export const mainPageUrl = "http://plush-toy.shop/" //get main page's content
export const addToCartUrl = "http://plush-toy.shop/cart/" //add a product to cart PUT
export const getCartUrl = "http://plush-toy.shop/cart/" //get a products from cart GET
export const sendFeedbackUrl = "http://plush-toy.shop/feedback/" //send a feedback